### PR TITLE
Convert schemas with x-ms-enum's modelAsString: true to ChoiceSchema

### PR DESCRIPTION
**Pull request by daviwil**
This change addresses issue #206 which reports that schemas with a single `enum` value and `x-ms-enum`'s `modelAsString` property set to `true` would be treated as `ConstantSchema` rather than `ChoiceSchema`.  The fix in this change comes from @fearthecowboy's PR #215 with some unit tests added.

I've also bumped the version to `4.15.0` because this is a breaking change.

/cc @srnagar

### CODE REVIEW

**Comment by daviwil** [comment]
@iscai-msft This change causes a change in the output of the Python generator (as expected, this is a breaking change):

https://dev.azure.com/azure-sdk/public/_build/results?buildId=438568&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=bd05475d-acb5-5619-3ccb-c46842dbc997&l=31.  

Do you think this is the expected result of `modelAsString` enums being changed from `ConstantSchema` to `ChoiceSchema`?

**Comment by daviwil** [comment]
Also, @srnagar was able to verify that this fixes the reported issue for the Java generator.

**Comment by srnagar** [comment]
@daviwil Thanks for the fix. Here's the generated code for Java before and after the fix:

Before:
```java
@JsonProperty(value = "charFilters")
private List<String> charFilters;
```
 
After:
```java
@JsonProperty(value = "charFilters")
private List<CharFilterName> charFilters;
```

**Comment by daviwil** [comment]
This seems to be working well with @lmazuel's new `constant.json` spec in https://github.com/Azure/autorest.testserver/pull/195 so I'm going to merge it.  Thanks all!

**Pull request merged**
