### PR TITLE
Update @autorest/compare, add regression-compare.yaml configuration

### PR DESCRIPTION
**Pull request by daviwil**
This change updates `@autorest/compare` to 0.2.0 which adds the ability to use a configuration file (`.scripts/regression-compare.yaml`) to configure the set of languages and specs that are run in regression tests.  ~I've used this configuration to generate baseline output from the TypeScript generator for regression tests.  It produced a lot of files, so let me know if you think it's overkill and perhaps we can find another way to do it (maybe a separate shared repo?)~

Pre-generated baseline output was removed from this PR due to the lack of substantive runtime reduction, see the first comment below.

### CODE REVIEW

**Comment by daviwil** [comment]
One interesting thing to note here is that having pre-generated baselines doesn't seem to improve the regression test runtime enough to warrant having them:

- CI regression test run [before baselines](https://dev.azure.com/azure-sdk/public/_build/results?buildId=251741&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=bd05475d-acb5-5619-3ccb-c46842dbc997): **5m 32s**
- CI regression test run [after baselines](https://dev.azure.com/azure-sdk/public/_build/results?buildId=253763&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=bd05475d-acb5-5619-3ccb-c46842dbc997): **5m 5s**

Not sure if the 27 second improvement was due to agent load variance or a result of not running the two AutoRest processes in parallel.  Maybe it's not worth using pregenerated baselines until more specs are added (especially those from azure-rest-api-specs)?

**Comment by fearthecowboy** [comment]
I'm wondering if parallelizing the tests would be better than pre-generated baselines?

I know that it's possible with ADO, but haven't done it.

**Comment by fearthecowboy** [comment]
> Maybe it's not worth using pregenerated baselines until more specs are added 

I'm starting to think maybe we shouldn't pregenerate -- if we break something in a back-compat scenario, we won't know without regenerating both.

**Comment by daviwil** [comment]
That's a good point.  I'll get rid of the pregenerated baselines for now until we can think of a compelling reason to include them.

Regarding parallel execution in ADO, I'm going to try that for running regression tests for the individual languages side-by-side.  We'll see how that goes when I get Python support added soon.

**Pull request merged**
