### PR TITLE
Allow binary files with json content type

### LINKED ISSUE #3631: Inconsistent `knownMediaType` produced for `"type": "string", "format": "binary"` json values
```
{
  "swagger": "2.0",
  "info": {
    "title": "JsonAsBinary",
    "description": "JsonAsBinary",
    "version": "1.0.0"
  },
  "host": "localhost:3000",
  "schemes": [
    "http"
  ],
  "produces": [
    "application/json"
  ],
  "consumes": [
    "application/json"
  ],
  "paths": {
    "/Operation/": {
      "put": {
        "operationId": "Operation",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "string",
              "format": "binary"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "type": "string",
              "format": "binary"
            }
          }
        }
      }
    }
  }
}
```

```
       protocol: !<!Protocols> 
              http: !<!HttpWithBodyRequest> 
                path: /Operation/
                method: put
                knownMediaType: json <----------
                mediaTypes:
                  - application/json
                uri: '{$host}'
        signatureParameters: []
        responses:
          - !<!BinaryResponse> 
            binary: true
            language: !<!Languages> 
              default:
                name: ''
                description: ''
            protocol: !<!Protocols> 
              http: !<!HttpBinaryResponse> 
                knownMediaType: binary <----------
                mediaTypes:
                  - application/json
                statusCodes:
                  - '200'
```

### LINKED ISSUE #3714: mark objects as binary if specified as file
If someone marks something as a file, regardless of content type in consumes / produces, we should just mark it as binary.

Currently semi-blocking @tasherif-msft (there can be temp swagger changes / change the generated code, but ideally would be fixed in autorest)

m4 output:
image

### PR DESCRIPTION
**Pull request by timotheeguerin**
fix Azure/autorest#3714
fix Azure/autorest#3631 

Comparaison of model before(left) and after(right)
image

### CODE REVIEW

**Comment by daviwil** [comment]
@iscai-msft - When you have a moment can you give the build above a try to see if it resolves the issue you reported?  Thanks!

**Review by daviwil — APPROVED** [review]
Nice work!  We can merge it after Isabella confirms the fix.

**Comment by daviwil** [comment]
I feel pretty sure this fix will work so I'm going to go ahead and merge it.  If we need to fix some more things related to it, we can do it in a different PR.

**Comment by iscai-msft** [comment]
thank you so so much @timotheeguerin and @daviwil ! It looks good to me, @tasherif-msft for final confirmation

**Comment by iscai-msft** [comment]
@tasherif-msft has also confirmed the fix worked!

**Pull request merged**
